services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: faz-waz-real-estate
    ports:
      - 33060:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin
    platform: linux/x86_64
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8089:80"

  nextjs:
    container_name: faz-waz-realestate-app-container
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/faz-waz-real-estate
      - NEXT_PUBLIC_URL=http://localhost:3000
    depends_on:
      - mysql
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && yarn dev"

volumes:
  mysql-data: