version: '3.9'

services:

  # Uncomment and modify the following block if you want to use MySQL

  db-stamps:
    image: mysql:8.0.28
    platform: linux/x86_64
    container_name: db-stamps
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DB: faz-waz-real-estate
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - default
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  # Uncomment and modify the following block if you want to use Next.js
  nextjs:
    container_name: faz-waz-realestate-app-container
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:password@db-stamps:3306/faz-waz-real-estate
      - NEXT_PUBLIC_URL=http://localhost:3000
    depends_on:
      - db-stamps
    command: sh -c "until npx prisma migrate deploy; do echo 'Waiting for the database...'; sleep 5; done && npx prisma db seed && yarn start"


  phpmyadmin:
    image: phpmyadmin
    platform: linux/x86_64
    restart: always
    environment:
      PMA_HOST: db-stamps
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8089:80"

networks:
  default:

volumes:
  dbdata:
    driver: local