
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: faz-waz-real-estate
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  nextjs:
    container_name: faz-waz-realestate-app-container
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/faz-waz-real-estate
      - NEXT_PUBLIC_URL=http:localhost:3000
    depends_on:
      - mysql
    command: sh -c "yarn install && npx prisma generate && until npx prisma migrate dev; do echo 'Waiting for the database...'; sleep 5; done && yarn dev"
volumes:
  mysql-data: